name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install backend dependencies
        run: |
          cd webserver
          npm install
          npm install -g firebase-tools
          npm install -g mocha
      - name: Run backend tests
        env:
          JWT_PRIVATE_KEY: ${{ vars.DUMMY_RSA_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ vars.DUMMY_RSA_PUBLIC_KEY }}
          ENV: dev
        run: | 
          cd webserver
          firebase emulators:exec --project test "mocha ./test/* --exit"
      - name: Install frontend dependencies
        run: |
          cd webapp
          npm install
      - name: e2e tests
        uses: cypress-io/github-action@v5
        env:
          JWT_PRIVATE_KEY: ${{ vars.DUMMY_RSA_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ vars.DUMMY_RSA_PUBLIC_KEY }}
          ENV: dev
        with:
          start: |
            cd ..
            cd webserver
            firebase emulators:exec --project test "node startserver & cd .. && cd webapp && npm start"
          wait-on: 'http://localhost:3000'
          browser: chrome
          working-directory: ./webapp
          